export class Town {
	constructor(public name: string) { }
}
export const towns: Town[] = [
	{ name: 'Akaa' },
	{ name: 'Alajärvi' },
	{ name: 'Alavieska' },
	{ name: 'Alavus' },
	{ name: 'Asikkala' },
	{ name: 'Askola' },
	{ name: 'Aura' },
	{ name: 'Enonkoski' },
	{ name: 'Enontekiö' },
	{ name: 'Espoo' },
	{ name: 'Eura' },
	{ name: 'Eurajoki' },
	{ name: 'Evijärvi' },
	{ name: 'Forssa' },
	{ name: 'Haapajärvi' },
	{ name: 'Haapavesi' },
	{ name: 'Hailuoto' },
	{ name: 'Halsua' },
	{ name: 'Hamina' },
	{ name: 'Hankasalmi' },
	{ name: 'Hanko' },
	{ name: 'Harjavalta' },
	{ name: 'Hartola' },
	{ name: 'Hattula' },
	{ name: 'Hausjärvi' },
	{ name: 'Heinola' },
	{ name: 'Heinävesi' },
	{ name: 'Helsinki' },
	{ name: 'Hirvensalmi' },
	{ name: 'Hollola' },
	{ name: 'Honkajoki' },
	{ name: 'Huittinen' },
	{ name: 'Humppila' },
	{ name: 'Hyrynsalmi' },
	{ name: 'Hyvinkää' },
	{ name: 'Hämeenkyrö' },
	{ name: 'Hämeenlinna' },
	{ name: 'Ii' },
	{ name: 'Iisalmi' },
	{ name: 'Iitti' },
	{ name: 'Ikaalinen' },
	{ name: 'Ilmajoki' },
	{ name: 'Ilomantsi' },
	{ name: 'Imatra' },
	{ name: 'Inari' },
	{ name: 'Inkoo' },
	{ name: 'Isojoki' },
	{ name: 'Isokyrö' },
	{ name: 'Janakkala' },
	{ name: 'Joensuu' },
	{ name: 'Jokioinen' },
	{ name: 'Joroinen' },
	{ name: 'Joutsa' },
	{ name: 'Juuka' },
	{ name: 'Juupajoki' },
	{ name: 'Juva' },
	{ name: 'Jyväskylä' },
	{ name: 'Jämijärvi' },
	{ name: 'Jämsä' },
	{ name: 'Järvenpää' },
	{ name: 'Kaarina' },
	{ name: 'Kaavi' },
	{ name: 'Kajaani' },
	{ name: 'Kalajoki' },
	{ name: 'Kangasala' },
	{ name: 'Kangasniemi' },
	{ name: 'Kankaanpää' },
	{ name: 'Kannonkoski' },
	{ name: 'Kannus' },
	{ name: 'Karijoki' },
	{ name: 'Karkkila' },
	{ name: 'Karstula' },
	{ name: 'Karvia' },
	{ name: 'Kaskinen' },
	{ name: 'Kauhajoki' },
	{ name: 'Kauhava' },
	{ name: 'Kauniainen' },
	{ name: 'Kaustinen' },
	{ name: 'Keitele' },
	{ name: 'Kemi' },
	{ name: 'Kemijärvi' },
	{ name: 'Keminmaa' },
	{ name: 'Kemiönsaari' },
	{ name: 'Kempele' },
	{ name: 'Kerava' },
	{ name: 'Keuruu' },
	{ name: 'Kihniö' },
	{ name: 'Kinnula' },
	{ name: 'Kirkkonummi' },
	{ name: 'Kitee' },
	{ name: 'Kittilä' },
	{ name: 'Kiuruvesi' },
	{ name: 'Kivijärvi' },
	{ name: 'Kokemäki' },
	{ name: 'Kokkola' },
	{ name: 'Kolari' },
	{ name: 'Konnevesi' },
	{ name: 'Kontiolahti' },
	{ name: 'Korsnäs' },
	{ name: 'Koski Tl' },
	{ name: 'Kotka' },
	{ name: 'Kouvola' },
	{ name: 'Kristiinankaupunki' },
	{ name: 'Kruunupyy' },
	{ name: 'Kuhmo' },
	{ name: 'Kuhmoinen' },
	{ name: 'Kuopio' },
	{ name: 'Kuortane' },
	{ name: 'Kurikka' },
	{ name: 'Kustavi' },
	{ name: 'Kuusamo' },
	{ name: 'Kyyjärvi' },
	{ name: 'Kärkölä' },
	{ name: 'Kärsämäki' },
	{ name: 'Lahti' },
	{ name: 'Laihia' },
	{ name: 'Laitila' },
	{ name: 'Lapinjärvi' },
	{ name: 'Lapinlahti' },
	{ name: 'Lappajärvi' },
	{ name: 'Lappeenranta' },
	{ name: 'Lapua' },
	{ name: 'Laukaa' },
	{ name: 'Lemi' },
	{ name: 'Lempäälä' },
	{ name: 'Leppävirta' },
	{ name: 'Lestijärvi' },
	{ name: 'Lieksa' },
	{ name: 'Lieto' },
	{ name: 'Liminka' },
	{ name: 'Liperi' },
	{ name: 'Lohja' },
	{ name: 'Loimaa' },
	{ name: 'Loppi' },
	{ name: 'Loviisa' },
	{ name: 'Luhanka' },
	{ name: 'Lumijoki' },
	{ name: 'Luoto' },
	{ name: 'Luumäki' },
	{ name: 'Maalahti' },
	{ name: 'Marttila' },
	{ name: 'Masku' },
	{ name: 'Merijärvi' },
	{ name: 'Merikarvia' },
	{ name: 'Miehikkälä' },
	{ name: 'Mikkeli' },
	{ name: 'Muhos' },
	{ name: 'Multia' },
	{ name: 'Muonio' },
	{ name: 'Mustasaari' },
	{ name: 'Muurame' },
	{ name: 'Mynämäki' },
	{ name: 'Myrskylä' },
	{ name: 'Mäntsälä' },
	{ name: 'Mänttä-Vilppula' },
	{ name: 'Mäntyharju' },
	{ name: 'Naantali' },
	{ name: 'Nakkila' },
	{ name: 'Nivala' },
	{ name: 'Nokia' },
	{ name: 'Nousiainen' },
	{ name: 'Nurmes' },
	{ name: 'Nurmijärvi' },
	{ name: 'Närpiö' },
	{ name: 'Orimattila' },
	{ name: 'Oripää' },
	{ name: 'Orivesi' },
	{ name: 'Oulainen' },
	{ name: 'Oulu' },
	{ name: 'Outokumpu' },
	{ name: 'Padasjoki' },
	{ name: 'Paimio' },
	{ name: 'Paltamo' },
	{ name: 'Parainen' },
	{ name: 'Parikkala' },
	{ name: 'Parkano' },
	{ name: 'Pedersöre' },
	{ name: 'Pelkosenniemi' },
	{ name: 'Pello' },
	{ name: 'Perho' },
	{ name: 'Pertunmaa' },
	{ name: 'Petäjävesi' },
	{ name: 'Pieksämäki' },
	{ name: 'Pielavesi' },
	{ name: 'Pietarsaari' },
	{ name: 'Pihtipudas' },
	{ name: 'Pirkkala' },
	{ name: 'Polvijärvi' },
	{ name: 'Pomarkku' },
	{ name: 'Pori' },
	{ name: 'Pornainen' },
	{ name: 'Porvoo' },
	{ name: 'Posio' },
	{ name: 'Pudasjärvi' },
	{ name: 'Pukkila' },
	{ name: 'Punkalaidun' },
	{ name: 'Puolanka' },
	{ name: 'Puumala' },
	{ name: 'Pyhtää' },
	{ name: 'Pyhäjoki' },
	{ name: 'Pyhäjärvi' },
	{ name: 'Pyhäntä' },
	{ name: 'Pyhäranta' },
	{ name: 'Pälkäne' },
	{ name: 'Pöytyä' },
	{ name: 'Raahe' },
	{ name: 'Raasepori' },
	{ name: 'Raisio' },
	{ name: 'Rantasalmi' },
	{ name: 'Ranua' },
	{ name: 'Rauma' },
	{ name: 'Rautalampi' },
	{ name: 'Rautavaara' },
	{ name: 'Rautjärvi' },
	{ name: 'Reisjärvi' },
	{ name: 'Riihimäki' },
	{ name: 'Ristijärvi' },
	{ name: 'Rovaniemi' },
	{ name: 'Ruokolahti' },
	{ name: 'Ruovesi' },
	{ name: 'Rusko' },
	{ name: 'Rääkkylä' },
	{ name: 'Saarijärvi' },
	{ name: 'Salla' },
	{ name: 'Salo' },
	{ name: 'Sastamala' },
	{ name: 'Sauvo' },
	{ name: 'Savitaipale' },
	{ name: 'Savonlinna' },
	{ name: 'Savukoski' },
	{ name: 'Seinäjoki' },
	{ name: 'Sievi' },
	{ name: 'Siikainen' },
	{ name: 'Siikajoki' },
	{ name: 'Siikalatva' },
	{ name: 'Siilinjärvi' },
	{ name: 'Simo' },
	{ name: 'Sipoo' },
	{ name: 'Siuntio' },
	{ name: 'Sodankylä' },
	{ name: 'Soini' },
	{ name: 'Somero' },
	{ name: 'Sonkajärvi' },
	{ name: 'Sotkamo' },
	{ name: 'Sulkava' },
	{ name: 'Suomussalmi' },
	{ name: 'Suonenjoki' },
	{ name: 'Sysmä' },
	{ name: 'Säkylä' },
	{ name: 'Taipalsaari' },
	{ name: 'Taivalkoski' },
	{ name: 'Taivassalo' },
	{ name: 'Tammela' },
	{ name: 'Tampere' },
	{ name: 'Tervo' },
	{ name: 'Tervola' },
	{ name: 'Teuva' },
	{ name: 'Tohmajärvi' },
	{ name: 'Toholampi' },
	{ name: 'Toivakka' },
	{ name: 'Tornio' },
	{ name: 'Turku' },
	{ name: 'Tuusniemi' },
	{ name: 'Tuusula' },
	{ name: 'Tyrnävä' },
	{ name: 'Ulvila' },
	{ name: 'Urjala' },
	{ name: 'Utajärvi' },
	{ name: 'Utsjoki' },
	{ name: 'Uurainen' },
	{ name: 'Uusikaarlepyy' },
	{ name: 'Uusikaupunki' },
	{ name: 'Vaala' },
	{ name: 'Vaasa' },
	{ name: 'Valkeakoski' },
	{ name: 'Valtimo' },
	{ name: 'Vantaa' },
	{ name: 'Varkaus' },
	{ name: 'Vehmaa' },
	{ name: 'Vesanto' },
	{ name: 'Vesilahti' },
	{ name: 'Veteli' },
	{ name: 'Vieremä' },
	{ name: 'Vihti' },
	{ name: 'Viitasaari' },
	{ name: 'Vimpeli' },
	{ name: 'Virolahti' },
	{ name: 'Virrat' },
	{ name: 'Vöyri' },
	{ name: 'Ylitornio' },
	{ name: 'Ylivieska' },
	{ name: 'Ylöjärvi' },
	{ name: 'Ypäjä' },
	{ name: 'Ähtäri' },
	{ name: 'Äänekoski' },
];

export const townsArray = [
	'Akaa',
	'Alajärvi',
	'Alavieska',
	'Alavus',
	'Asikkala',
	'Askola',
	'Aura',
	'Enonkoski',
	'Enontekiö',
	'Espoo',
	'Eura',
	'Eurajoki',
	'Evijärvi',
	'Forssa',
	'Haapajärvi',
	'Haapavesi',
	'Hailuoto',
	'Halsua',
	'Hamina',
	'Hankasalmi',
	'Hanko',
	'Harjavalta',
	'Hartola',
	'Hattula',
	'Hausjärvi',
	'Heinola',
	'Heinävesi',
	'Helsinki',
	'Hirvensalmi',
	'Hollola',
	'Honkajoki',
	'Huittinen',
	'Humppila',
	'Hyrynsalmi',
	'Hyvinkää',
	'Hämeenkyrö',
	'Hämeenlinna',
	'Ii',
	'Iisalmi',
	'Iitti',
	'Ikaalinen',
	'Ilmajoki',
	'Ilomantsi',
	'Imatra',
	'Inari',
	'Inkoo',
	'Isojoki',
	'Isokyrö',
	'Janakkala',
	'Joensuu',
	'Jokioinen',
	'Joroinen',
	'Joutsa',
	'Juuka',
	'Juupajoki',
	'Juva',
	'Jyväskylä',
	'Jämijärvi',
	'Jämsä',
	'Järvenpää',
	'Kaarina',
	'Kaavi',
	'Kajaani',
	'Kalajoki',
	'Kangasala',
	'Kangasniemi',
	'Kankaanpää',
	'Kannonkoski',
	'Kannus',
	'Karijoki',
	'Karkkila',
	'Karstula',
	'Karvia',
	'Kaskinen',
	'Kauhajoki',
	'Kauhava',
	'Kauniainen',
	'Kaustinen',
	'Keitele',
	'Kemi',
	'Kemijärvi',
	'Keminmaa',
	'Kemiönsaari',
	'Kempele',
	'Kerava',
	'Keuruu',
	'Kihniö',
	'Kinnula',
	'Kirkkonummi',
	'Kitee',
	'Kittilä',
	'Kiuruvesi',
	'Kivijärvi',
	'Kokemäki',
	'Kokkola',
	'Kolari',
	'Konnevesi',
	'Kontiolahti',
	'Korsnäs',
	'Koski Tl',
	'Kotka',
	'Kouvola',
	'Kristiinankaupunki',
	'Kruunupyy',
	'Kuhmo',
	'Kuhmoinen',
	'Kuopio',
	'Kuortane',
	'Kurikka',
	'Kustavi',
	'Kuusamo',
	'Kyyjärvi',
	'Kärkölä',
	'Kärsämäki',
	'Lahti',
	'Laihia',
	'Laitila',
	'Lapinjärvi',
	'Lapinlahti',
	'Lappajärvi',
	'Lappeenranta',
	'Lapua',
	'Laukaa',
	'Lemi',
	'Lempäälä',
	'Leppävirta',
	'Lestijärvi',
	'Lieksa',
	'Lieto',
	'Liminka',
	'Liperi',
	'Lohja',
	'Loimaa',
	'Loppi',
	'Loviisa',
	'Luhanka',
	'Lumijoki',
	'Luoto',
	'Luumäki',
	'Maalahti',
	'Marttila',
	'Masku',
	'Merijärvi',
	'Merikarvia',
	'Miehikkälä',
	'Mikkeli',
	'Muhos',
	'Multia',
	'Muonio',
	'Mustasaari',
	'Muurame',
	'Mynämäki',
	'Myrskylä',
	'Mäntsälä',
	'Mänttä-Vilppula',
	'Mäntyharju',
	'Naantali',
	'Nakkila',
	'Nivala',
	'Nokia',
	'Nousiainen',
	'Nurmes',
	'Nurmijärvi',
	'Närpiö',
	'Orimattila',
	'Oripää',
	'Orivesi',
	'Oulainen',
	'Oulu',
	'Outokumpu',
	'Padasjoki',
	'Paimio',
	'Paltamo',
	'Parainen',
	'Parikkala',
	'Parkano',
	'Pedersöre',
	'Pelkosenniemi',
	'Pello',
	'Perho',
	'Pertunmaa',
	'Petäjävesi',
	'Pieksämäki',
	'Pielavesi',
	'Pietarsaari',
	'Pihtipudas',
	'Pirkkala',
	'Polvijärvi',
	'Pomarkku',
	'Pori',
	'Pornainen',
	'Porvoo',
	'Posio',
	'Pudasjärvi',
	'Pukkila',
	'Punkalaidun',
	'Puolanka',
	'Puumala',
	'Pyhtää',
	'Pyhäjoki',
	'Pyhäjärvi',
	'Pyhäntä',
	'Pyhäranta',
	'Pälkäne',
	'Pöytyä',
	'Raahe',
	'Raasepori',
	'Raisio',
	'Rantasalmi',
	'Ranua',
	'Rauma',
	'Rautalampi',
	'Rautavaara',
	'Rautjärvi',
	'Reisjärvi',
	'Riihimäki',
	'Ristijärvi',
	'Rovaniemi',
	'Ruokolahti',
	'Ruovesi',
	'Rusko',
	'Rääkkylä',
	'Saarijärvi',
	'Salla',
	'Salo',
	'Sastamala',
	'Sauvo',
	'Savitaipale',
	'Savonlinna',
	'Savukoski',
	'Seinäjoki',
	'Sievi',
	'Siikainen',
	'Siikajoki',
	'Siikalatva',
	'Siilinjärvi',
	'Simo',
	'Sipoo',
	'Siuntio',
	'Sodankylä',
	'Soini',
	'Somero',
	'Sonkajärvi',
	'Sotkamo',
	'Sulkava',
	'Suomussalmi',
	'Suonenjoki',
	'Sysmä',
	'Säkylä',
	'Taipalsaari',
	'Taivalkoski',
	'Taivassalo',
	'Tammela',
	'Tampere',
	'Tervo',
	'Tervola',
	'Teuva',
	'Tohmajärvi',
	'Toholampi',
	'Toivakka',
	'Tornio',
	'Turku',
	'Tuusniemi',
	'Tuusula',
	'Tyrnävä',
	'Ulvila',
	'Urjala',
	'Utajärvi',
	'Utsjoki',
	'Uurainen',
	'Uusikaarlepyy',
	'Uusikaupunki',
	'Vaala',
	'Vaasa',
	'Valkeakoski',
	'Valtimo',
	'Vantaa',
	'Varkaus',
	'Vehmaa',
	'Vesanto',
	'Vesilahti',
	'Veteli',
	'Vieremä',
	'Vihti',
	'Viitasaari',
	'Vimpeli',
	'Virolahti',
	'Virrat',
	'Vöyri',
	'Ylitornio',
	'Ylivieska',
	'Ylöjärvi',
	'Ypäjä',
	'Ähtäri',
	'Äänekoski'
];
